spring:
  application:
    name: spring-boot-admin
  boot:
    admin:
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,turbine.stream
      turbine:
        clusters: default
        url: http://127.0.0.1:8004/turbine.stream
      client:
        prefer-ip: true
    mvc:
      async:
        request-timeout: -1
server:
  port: 8005
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka/

info:
  application:
    name: Spring Boot Admin管理中心
    version: 1.0-SNAPSHOT
    author: lujing