spring:
  application:
    name: account-ms
server:
  port: 8002
eureka:
  client:
    service-url:
#      defaultZone: 'http://eureka1:8763/eureka/,http://eureka2:8762/eureka/'
      defaultZone: http://127.0.0.1:8001/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1500
