spring:
  application:
    name: user-ms
  zipkin:
    base-url: http://127.0.0.1:8006/
server:
  port: 8003
eureka:
  client:
    service-url:
#      defaultZone: 'http://eureka1:8763/eureka/,http://eureka2:8762/eureka/'
      defaultZone: http://127.0.0.1:8001/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1500
feign:
  hystrix:
   enabled: true

info:
  application:
    name: user服务
    version: 1.0-SNAPSHOT
    author: lujing