spring:
  application:
    name: hystrix-ms
server:
  port: 8004
turbine:
  app-config: account-ms, user-ms
  aggregator:
    clusterConfig: default
  cluster-name-expression: metadata['cluster']
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka/

